INSERT INTO USER_LOGIN (USERNAME, PASSWORD) VALUES ('admin', 'admin1');

INSERT INTO PAYMENT  (TOTAL_PRICE) VALUES (100.0);

INSERT INTO ORDERS (ORDER_NAME, STATUS, REQUESTED_DATE,USER_LOGIN,PAYMENT) VALUES ('Regular','PAID', '2020-08-20',1,1);

INSERT INTO ORDER_ITEM  (ITEM_NAME, PRICE, IS_ACTIVE, Orders) VALUES ('MOMO', 100.0,true,1);

INSERT INTO ORDERS (ORDER_NAME, STATUS, REQUESTED_DATE,USER_LOGIN) VALUES ('Hari','OREDER_RECEIVED', '2020-08-20',1);

INSERT INTO ORDER_ITEM  (ITEM_NAME, PRICE, IS_ACTIVE, Orders) VALUES ('PIZZA', 250.0,true,2);

